import { Event } from "./interface";

export const events: Event[] = [
  {
    id: "4421cb3d-a0cf-4e29-8250-51767063cd62",
    artists: [{ name: "DJ's en vivo", description: "" }],
    category: "Sunset",
    collectionName: "Wine Activity #1",
    collectionSymbol: "WINE",
    createdAt: 1732388398000,
    date: "09 de Agosto, 2025",
    description:
      "Sunset wine & after orgnanizado por Paax Producciones.\n Degustación de más de 10 bodegas, plan Bonarda, dirección de Turismo y dirección de Cultura.\n YO 🤍 BONARDA",
    edition: 1,
    image: "/wine-activity-1.webp",
    location: "Centro de congreso y exposiciones Francisco",
    name: "Wine Activity",
    prs: [
      {
        id: "1",
        name: "Ana Paula Castillo",
        email: "Anapaulacastillo2323@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "2",
        name: "Emilia Suarez",
        email: "emiliasuarez818@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "3",
        name: "Agustina Chini",
        email: "agustinachini26@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "4",
        name: "Franco Pezutti",
        email: "pezuttifranco@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "5",
        name: "Tiago Carrasco",
        email: "Tiagoschoology@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "6",
        name: "Valentina Espin",
        email: "Valespin2001@icloud.com",
        phone: "",
        photo: "",
      },
      {
        id: "7",
        name: "Guadalupe Ledda",
        email: "Guadalupeledda010@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "8",
        name: "Chiara Onofri",
        email: "Onofrichiarii@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "9",
        name: "Melisa Penna",
        email: "pennamelisa@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "10",
        name: "Victoria Ramírez",
        email: "victoriamilagrosr@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "11",
        name: "Mavi Fontana",
        email: "Mavi.fontana.costa@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "12",
        name: "Zeki Rivas",
        email: "ribasezekiel@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "13",
        name: "Juan Vargas",
        email: "Juancito.vargass2@gmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "14",
        name: "Sabina Consoli",
        email: "consolini_96@hotmail.com",
        phone: "",
        photo: "",
      },
      {
        id: "15",
        name: "Candela Morello",
        email: "canndelamorello@gmail.com",
        phone: "",
        photo: "",
      },
    ],
    tickets: [
      {
        id: "d98c69a9-79f7-432c-a4f2-5e1e4bbd2cf5",
        name: "General",
        description: "Incluye copa de vino",
        // price: 17250,
        // tax: 2250,
        // priceWithoutTax: 15000,
        price: 172.5,
        tax: 22.5,
        priceWithoutTax: 150.0,
      },
    ],
    time: "19:00 hs - 02:00 hs",
  },
];
